package com.keerthimac.bill_tracker_system.mapper;

import com.keerthimac.bill_tracker_system.dto.MasterMaterialRequestDTO;
import com.keerthimac.bill_tracker_system.dto.MasterMaterialResponseDTO;
import com.keerthimac.bill_tracker_system.entity.MasterMaterial;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.Mappings; // For grouping multiple @Mapping annotations

import java.util.List;

@Mapper(componentModel = "spring", uses = {ItemCategoryMapper.class}) // Use ItemCategoryMapper for nested mapping
public interface MasterMaterialMapper {

    /**
     * Converts a MasterMaterial entity to a MasterMaterialResponseDTO.
     * The 'itemCategory' field will be mapped using ItemCategoryMapper.
     * @param masterMaterial The MasterMaterial entity.
     * @return The corresponding MasterMaterialResponseDTO.
     */
    // No explicit @Mapping needed for itemCategory if field names match and ItemCategoryMapper is in 'uses'
    // MapStruct will automatically use ItemCategoryMapper.toDto(masterMaterial.getItemCategory())
    MasterMaterialResponseDTO toDto(MasterMaterial masterMaterial);

    /**
     * Converts a list of MasterMaterial entities to a list of MasterMaterialResponseDTOs.
     * @param masterMaterials The list of MasterMaterial entities.
     * @return The list of corresponding MasterMaterialResponseDTOs.
     */
    List<MasterMaterialResponseDTO> toDtoList(List<MasterMaterial> masterMaterials);

    /**
     * Converts a MasterMaterialRequestDTO to a MasterMaterial entity.
     * The 'itemCategory' entity itself will be set in the service layer using 'itemCategoryId' from the DTO.
     * 'id', 'createdAt', and 'updatedAt' are ignored as they are typically auto-generated or managed by JPA.
     * @param requestDTO The MasterMaterialRequestDTO.
     * @return The corresponding MasterMaterial entity.
     */
    @Mappings({
            @Mapping(target = "id", ignore = true),
            @Mapping(target = "itemCategory", ignore = true), // Service will set this using itemCategoryId
            @Mapping(target = "createdAt", ignore = true),    // Auto-generated by @CreationTimestamp
            @Mapping(target = "updatedAt", ignore = true)     // Auto-generated by @UpdateTimestamp
    })
    MasterMaterial toEntity(MasterMaterialRequestDTO requestDTO);
}
